[package]
name = "loot-and-roam"
version = "0.1.0"
edition = "2021"

[dependencies]
float-cmp = "0.9.0"
monoio = "0.2.3"
rayon = "1.10.0"
soa_derive = "0.13.0"
ultraviolet = "0.9.2"

[lib]
crate-type = ["cdylib", "rlib"]

[dev-dependencies]
assertables = "9.5.0"
