[package]
name = "loot-and-roam"
version = "0.1.0"
edition = "2021"

[dependencies]
enum_dispatch = "0.3.13"
float-cmp = "0.9.0"
generational-arena = "0.2.9"
itertools = "0.14.0"
monoio = "0.2.3"
num-integer = "0.1.46"
num-traits = "0.2.19"
slotmap = "1.0.7"
smallvec = "1.13.2"
soa_derive = "0.13.0"
ultraviolet = "0.9.2"

[lib]
crate-type = ["cdylib", "rlib"]

[dev-dependencies]
assertables = "9.5.0"
