name: Build Development Docker Image

on:
  push:
    branches:
      - main
    paths:
      - "docker/Dockerfile"
  workflow_dispatch:

jobs:
  build_and_push_image:
    name: Build & Push CI Image
    runs-on: codeberg-small-lazy
    steps:
      - name: Checkout Repository
        uses: https://code.forgejo.org/actions/checkout@v4

      - name: Log in to Container Registry
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and Push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: docker/Dockerfile
          push: true
          tags: |
            docker.io/${{ secrets.DOCKER_USERNAME }}/loot-and-roam-ci:latest # Tag as latest
            docker.io/${{ secrets.DOCKER_USERNAME }}/loot-and-roam-ci:${{ forge.sha }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
