name: Rust Lint & Test
on:
  push:
    branches:
      - main
  pull_request:
  workflow_dispatch:

jobs:
  test:
    name: Cargo check
    runs-on: codeberg-small-lazy
    container:
      image: docker.io/${{ secrets.DOCKER_USERNAME }}/loot-and-roam-ci:latest

    steps:
      - name: Run basic cargo linter
        run: "cargo check --no-default-features"

      - name: Run cargo-fmt linter
        run: "cargo fmt --check --no-default-features"

      - name: Run clippy linter
        run: "cargo clippy --no-default-features"

      - name: Run tests
        run: "cargo test --no-default-features"
